### ISSUE TITLE
Localization readme is ambigious

### ISSUE THREAD

**Issue by kandelvijaya** [usabilla/usabilla-u4a-ios-swift-sdk#111]
The readme puts:
```
Localisation

For all the text that is not customizable in the web interface, you can provide your own translation using a `.string` localized file inside your application.
```

Does `.string` mean `.strings` ??

**Comment by tzengerink** [comment]
@kandelvijaya We mean `.string` here.

Are you having issues setting up the localisation? What are the problems you're having?

**Comment by kandelvijaya** [comment]
Hi there, thanks for the support. 

Let me clarify what I got:
1. Add `xyz.string` file in the target bundle.
2. In the code
```swift
Usabilla.localizedStringFile = "xyz"
/// loadFeedbackForm
```

Question:
1. How do I supply multiple country specific localization keys. 
   IF I could provide `xyz.strings` file then it can internally have `xyz.strings(German)` and `xyz.strings(English)`. However, with `.string` files we can't.

**Comment by kandelvijaya** [comment]
@tzengerink Yup. using the `.strings` file is naturally a better fit for localization.

 I did try using the `.strings` file (this is how we localize our app now). This, unfortunately, didn't work as well. 

Since its a binary I don't know what's the missing part here.

**Comment by tzengerink** [comment]
@kandelvijaya Just to make sure I understand your issue and the supplied proposal:

You want to be able to target your users based on the language setting within the app, not just on the language setting stored on the device. You want to achieve this because you don't want to, for example, send a German form to an English speaking expat in Germany. Correct?

I'll mark this as a feature request, so we can keep track of this use case and your proposed solution. Thanks for the suggestion.

**Comment by kandelvijaya** [comment]
That is correct. 

The implementation could be clean if a struct containing keys as properties is required by delegate requirement. 

Thanks for taking input.

**Comment by torkvell** [comment]
@kandelvijaya,

This feature request has been registered on our end. I will now close this ticket. If you have any other feedback, please let us know.
