### ISSUE TITLE
Updating legacy code

### ISSUE THREAD

**Issue by StammTom** [usabilla/usabilla-u4a-ios-swift-sdk#114]
I am updating some legacy code (written by others) to xcode 10, Swift 12 and am getting an error on "hideGiveMoreFreeback".  Can anyone suggest replacement code or a safe way of dealing with it?
I do know the the preloadForms function is renamed.
<img width="901" alt="screen shot 2018-10-01 at 4 56 19 pm" src="https://user-images.githubusercontent.com/42014469/46322077-c1649f80-c59b-11e8-96fd-37529ea865d3.png">
Thanks in advance.
Tom

**Comment by tzengerink** [comment]
@StammTom In order to remove these errors you should remove the line containing `Usabilla.hideGiveMoreFeedback = true`, since it was removed in [v5.0.0](https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/releases/tag/v5.0.0). The `preloadForms` method was indeed renamed to `preloadFeedbackForms`.

**Comment by StammTom** [comment]
Thank you.
