### ISSUE TITLE
Build errors for Xcode 11 GM

### ISSUE THREAD

**Issue by donnywdavis** [usabilla/usabilla-u4a-ios-swift-sdk#151]
Using the `v6.4.0-Xcode-11-GM` build I am getting a couple of issues.

* It skips installing the framework due to incompatible swift version:
`"Incompatible Swift version - framework was built with 5.1 (swiftlang-1100.0.270.6 clang-1100.0.32.1) and the local version is 5.1 (swiftlang-1100.0.270.13 clang-1100.0.33.7)."`

* It skips building due to no shared frameworks for schemes:
`Dependency "usabilla-u4a-ios-swift-sdk" has no shared framework schemes for any of the platforms: iOS`

I tried to use the `beta7` build and get the same error. I already had `beta7` built for the previous Xcode beta and that seems to work fine with the GM. I can compile our project and run it with no issues. I only get these errors when trying to update dependencies with the Xcode 11 GM (11A419c) command line tools selected.

**Comment by farhad-ris** [comment]
I've got the same issue `Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1 compiler: ~/Pods/Usabilla/Usabilla.framework/Modules/Usabilla.swiftmodule/x86_64.swiftmodule`

We are about to release our iOS 13 compatible app and blocked by Usabilla SDK

**Comment by teameh** [comment]
Even with the errors fixed, note that the `v6.4.0-Xcode-11-GM` release is not production ready according to the [release page](https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/releases/tag/v6.4.0-Xcode-11-GM).

**Comment by MaximBazarov** [comment]
@teameh the original issue is in **v6.4.0-Xcode-11-GM** with **Xcode-11-GM**, it says that you need to check 'Shared` checkmark in your framework Xcode projects, for all platforms

**Comment by MaximBazarov** [comment]
also might be helpful to rebuild it with the latest Xcode GM seed 2 since you don't open source code

**Comment by torkvell** [comment]
Hi all,

Thanks for your patience on this. I'm happy to assist with this.

**@donnywdavis:**
- `It skips installing the framework due to incompatible swift version:` You have to update your Xcode version. This error is caused by an incompatibility between the compile version for the SDK and the compiler you have in your Xcode version.

`- It skips building due to no shared frameworks for schemes: `You need to link the SDK in the linked frameworks and library:
![2019-09-17 at 16 29](https://user-images.githubusercontent.com/40064170/65050891-6c669880-d968-11e9-8603-40fa32f1653a.png)

**@farhad-ris:**
The GM version is not a production-ready release, so you can't do this through normal ways using`pod update`. However, what you can do is to point directly to the GitHub repo in your podfile: 
```pod 'Usabilla', :git => 'https://github.com/usabilla/usabilla-u4a-ios-swift-sdk.git', :tag => 'v6.4.0-Xcode-11-GM'```. Another workaround is to download the framework directly from the repo and then include it in your project.

I hope this helps. Please let me know if there is anything else.

**Comment by MaximBazarov** [comment]
Hi @torkvell the problem is that GM requires it to be built with the latest version of Xcode, now it's GM Seed 2 (yeah I know). that version you referring to doesn't fit. I think you should rebuild it again and release.

**Comment by MaximBazarov** [comment]
btw for cartage users, the workaround would be:
1. update dependencies with Carthage
2. Copy the unpacked content of  `Carthage.framework.zip` [download here](https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/releases/tag/v6.4.0-Xcode-11-GM )
to  `<SRC_ROOT>/‎⁨Carthage⁩/Build⁩/iOS⁩

**Comment by donnywdavis** [comment]
@torkvell Thanks for the comments. That was why I opened the issue. I am running the latest Xcode version which is the GM and updated our `cartfile` to point to `v6.4.0-Xcode-11-GM` and I still get those errors. 

For some reason Usabilla is not showing under `Linked Frameworks and Libraries`. I'm investigating that to find out why. But it has been that way for a while now it seems and was building fine on the previous Xcode betas. Not sure what changed that it would all of a sudden start failing now. 🤔

If I just build our project with the `v6.4.0-Xcode-11-beta7` version that we already have installed then our project builds and runs fine. We just can't run `carthage update` at the moment with Xcode 11 GM b/c of those errors I mentioned.

**Comment by donnywdavis** [comment]
The latest release `v6.4.0-Xcode-11` seems to work with GM seed 2.

**Comment by torkvell** [comment]
Hi @donnywdavis ,

This is a production ready release yes. Happy coding!

Let us know if there is anything else we can assist on.
