### ISSUE TITLE
Why do Usabilla SDK keeps breaking my automated builds?

### ISSUE THREAD

**Issue by ushafiq** [usabilla/usabilla-u4a-ios-swift-sdk#16]
I noticed this morning that UsabillaThemeConfigurator has change quite a bit and it caused my automated build to fail on the server. I would assume it to be deprecated instead.

**Comment by gPinato** [comment]
Are you using v 3.0 of the SDK?

**Comment by ushafiq** [comment]
I am just using latest via cocoapod

**Comment by ushafiq** [comment]
pod 'UsabillaFeedbackForm', :git => 'https://github.com/usabilla/usabilla-u4a-ios-swift-sdk.git'

**Comment by gPinato** [comment]
Ah yeah I confused the SDKs. The SDK v 2.2 enables support for color customisation from our backend. To support that the Theme Configurator had to be reworked.
It is stated in the changelog
* Colour customisation from the Usabilla web interface is now supported
* Reworked the theme configuration, now every form has its own configuration object


You can either
* specify  :tag=>'v2.1' in your podfile to keep using the old version
* use directly `pod 'UsabillaFeedbackForm', '2.1'` since now the pod is the cocoapods master repo
* Update your implementation. The only difference is that now the object is not a shared singleton. Now every form has his own configuration, passed when you call `loadFeedbackForm`.

**Comment by ushafiq** [comment]
Thank you for your response gPinato. I start using SDK 2.1 now, and everything seems to work.

**Comment by gPinato** [comment]
No problem, you're welcome.
