### ISSUE TITLE
Permissions needed

### ISSUE THREAD

**Issue by kernandreas** [usabilla/usabilla-u4a-ios-swift-sdk#164]
To support iOS 13 we were forced to update to the newest Usabilla version. This now requires to add the `NSCameraUsageDescription` and `NSPhotoLibraryUsageDescription`.
Is there an option to disable adding a screenshot or to use the `UIImagePickerController` instead of your own implementation?
Our main application does not need the permissions. And we do not want all the 3rd party dependencies to have access to the users camera and photos since this is a privacy problem.

**Comment by torkvell** [comment]
Hi @kernandreas ,

Pass `nil` as the screenshot parameter if you don't want to have a screenshot attached at all. 

Instead of taking the screenshot using the `Usabilla.takeScreenshot()` method, you can also provide any image you wish by passing it as the image parameter when calling `Usabilla.loadFeedbackForm()`

This will allow you to hide any user sensitive information by, for example, taking the screenshot yourself, removing all unwanted information and submitting the censored version.

I hope this helps. Let me know if you have any further questions.

**Comment by torkvell** [comment]
I would also like to point out a new section we have in our readme: https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/releases

What this essentially means, is that you still have to define the stings ```NSCameraUsageDescription``` ```NSPhotoLibraryUsageDescription```. These are needed since your application (containing our SDK) has a feature that could use them. These privacy permissions must be included to pass App-store reviews.

**Comment by kernandreas** [comment]
Thank you for the response and pointing out the "show screenshot" option. I think this will be the way the will test. Can you confirm, that the SDK will never try to access the photo library or the camera of the user? Because we do not want to add this permissions in our app. We are already searching for alternatives to Usabilla because of this.

As I mentioned there is no need to go this route. The Usabilla SDK could just use the `UIImagePickerController` to retrieve images from the user. Since iOS 11 there is no need to add `NSPhotoLibraryUsageDescription`. This is described in https://developer.apple.com/videos/play/wwdc2017/505/?time=141

**Comment by torkvell** [comment]
Hi @kernandreas ,

I can confirm we won't try to access the photo library or the camera of the user unless the feature is enabled and they themselves choose to give access so they can add photos themselves. Due to design choices, we've decided to not make use of the ```UIImagePickerController```, but instead, implement our own.

I hope this clarifies, if there is anything else, please let me know.

**Comment by kernandreas** [comment]
Thank you for clarifying this.
