### ISSUE TITLE
Campaign language targeting inaccurate

### ISSUE THREAD

**Issue by Goseong** [usabilla/usabilla-u4a-ios-swift-sdk#189]
Hi there, I'm running the following campaign which is targeting devices with the German language. However it's being triggered for devices in the English language as well. 

I can't remember whether you base this targeting setting on device language or region on iPhone X iOS 13.4.1 

8234991c-74e9-4df8-a63e-a5ac1d78ac28

Regards,

Tjerk

**Comment by Goseong** [comment]
Region is set to NL and the Language to English (UK).  SDK version 6.4.4
It's happening on multiple devices.

**Comment by lennardtastic** [comment]
Hi @Goseong ,

We checked our versioning and did some testing using the settings you provided. In version 6.4.5 of our SDK, we released some minor fixes for the language targeting. This could explain why you're experiencing the issues with the language targeting while using version 6.4.4 of the SDK.

I would recommend that you upgrade to the latest version of our SDK, based on our testing this should resolve the issue for you with the language targeting.
I'll close the issue now if the issue does surface again after the update please let me know so that I can reopen it.

Kind Regard,
Lennard
