### ISSUE TITLE
Host application non-interactible after scrolling form view controller.

### ISSUE THREAD

**Issue by jasonw6800** [usabilla/usabilla-u4a-ios-swift-sdk#190]
Usabilla renders the host application inoperable after attempting to scroll the form view controller.

SDK version: 6.4.5
iOS version: 13
Xcode version: 11.3.1

Steps to reproduce:
1.) Create campaign and trigger notification in host application
2.) Attempt to scroll the form
3.) EXPECTED: form view controller scrolls
4.) ACTUAL: view controller freezes in place, then disappears. The campaign window persists and the app is non-interactable.

Other notes:
- Updating the usabilla SDK to 6.4.6 and building with XCode 11.4 does not fix it, same behavior
- Testing a build on a physical device with iOS 12.4 -> the bug does not show up there
- Confirmed with simulators too that this is iOS 13 only

**Comment by lennardtastic** [comment]
Hi @jasonw6800,

Our developers are looking into the issue. If you have more information specific to your Usabilla implementation (campaign-id, App-ID etc.) that you could share, please share them with our Support team via support@usabilla.com.

Kind regards,
Lennard

**Comment by lennardtastic** [comment]
Hi @jasonw6800,

We've done some testing based on the issues that you reported. When we tried reproducing the issue by triggering a campaign and then clicking the feedback button from the internal app it was shown and scroll and all events were working perfectly on iOS 13. We were not able to reproduce the issue.
We would really appreciate it if you could reach out to our support team via support@usabilla.com. That will make the troubleshooting a bit easier and hopefully provide us with the necessary information to tackle the issue you're experiencing.

Kind regards,
Lennard

**Comment by kohanian** [comment]
Hi @lennardtastic 

Here is a gif of what @jasonw6800 is talking about. It's consistently reproducible with the Usabilla preview app. 
Try swiping down on the modal down half way and then let go. If you still aren't able to, then we'll reach out to the support team.

![usabilla_issue](https://user-images.githubusercontent.com/8570821/79896098-c3c85d80-83bc-11ea-8b7c-4ad3c0b03cde.gif)

**Comment by kohanian** [comment]
Hi @lennardtastic ,

I have a video that clearly documents this issue. I was able to reproduce it on the Usabilla preview application. Is there any way I can send you that video? I can't do it through here :(

**Comment by lennardtastic** [comment]
Hi @kohanian,

I don't know why but the video you posted actually does show in our Slack integration so we were able to check it out. Our developers are preparing a release for today that will most likely your issue. But since we were not able to reproduce your issue specifically, we would really appreciate it if you could confirm if the fix works for you. 
I'll let you know in this thread when the release is available.

Kind regard,
Lennard

**Comment by lennardtastic** [comment]
Hi All,

We released a new version of our SDK that addresses this issue. Please update to the latest SDK Version found on https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/releases. In the unfortunate event that the issue persists after updating to the latest release please let us know by replying in this thread so that I can reopen the issue.

Kind regards,
Lennard

**Comment by kohanian** [comment]
@lennardtastic 

Looks good in 6.4.7, thank you for your help!
