### ISSUE TITLE
Support for Xcode 12 / iOS 14 / Swift 5.3

### ISSUE THREAD

**Issue by klaasscho1** [usabilla/usabilla-u4a-ios-swift-sdk#202]
I'm trying to build an app for iOS 14 at the moment, but the Usabilla binary isn't compiled for Swift 5.3 yet. When are you planning to support these versions?

**Comment by lennardtastic** [comment]
Hi @klaasscho1,

Thank you for your message.

The Usabilla SDK Binary utilizes module stability to ensure that you can use the SDK regardless of the Swift version used for compiling. Our SDK is already compatible with Xcode 12 / iOS 14 / Swift 5.3 because of module stability. We've tested this for both Carthage and Cocoapods.

If you're getting the error it might be that you're using an outdated version of Carthage. It's only been since the latest release that Carthage added module stability support for binary frameworks. So if you haven't updated yet please do so (https://github.com/Carthage/Carthage/releases).

If you're not using Carthage but you're using a different package manager (or updated Carthage and you're stilling getting the issue). Please let us know so that we can investigate.

Best regards,
Lennard

**Comment by andlang** [comment]
I have Usabilla (v6.4.7-Xcode-11.5) manually installed (would prefer a SPM version) and I get the following error, when I try to make a release build (Build Configuration: Release) for the simulator in XCode 12.0 beta 6 (12A8189n):
```
Unable to load standard library for target 'arm64-apple-ios9.0'

Failed to build module 'Usabilla' from its module interface; the compiler that produced it, 'Apple Swift version 5.2.4 effective-4.1.50 (swiftlang-1103.0.32.9 clang-1103.0.32.53)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.3 effective-4.1.50 (swiftlang-1200.0.28.1 clang-1200.0.30.1)'
```
It works, when I change the build setting `ONLY_ACTIVE_ARCH` to `YES`. But that is only a workaround.
In XCode 11.6 I don’t have any problem with my setup.

Could you investigate this, please?

**Comment by lennardtastic** [comment]
Hi @andlang,

Thank you for your message. 

I'm fairly certain that the issue that you're having is not related to what was originally mentioned in this issue. 

Regardless, I'm happy to help you with the issue that you're experiencing. 

The issue that you're referring to is actually an Xcode issue that sometimes can occur for supported architecture. (Which you add by adding flags like `arm64 -arch armv7 -arch armv7s` )

Based on some threads online we suggest that you try the following
- Quitting Xcode
- Clean derived data 
- Do a build again 
This might solve your issue. Please let us know how it goes.

With regard to the SPM package, this will be available in the next release. 

Best regards,
Lennard

**Comment by lennardtastic** [comment]
Closing issue due to it being stale. Please open a new issue if you require further assistance.

**Comment by OmarJalil** [comment]
> I have Usabilla (v6.4.7-Xcode-11.5) manually installed (would prefer a SPM version) and I get the following error, when I try to make a release build (Build Configuration: Release) for the simulator in XCode 12.0 beta 6 (12A8189n):
> 
> ```
> Unable to load standard library for target 'arm64-apple-ios9.0'
> 
> Failed to build module 'Usabilla' from its module interface; the compiler that produced it, 'Apple Swift version 5.2.4 effective-4.1.50 (swiftlang-1103.0.32.9 clang-1103.0.32.53)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.3 effective-4.1.50 (swiftlang-1200.0.28.1 clang-1200.0.30.1)'
> ```
> 
> It works, when I change the build setting `ONLY_ACTIVE_ARCH` to `YES`. But that is only a workaround.
> In XCode 11.6 I don’t have any problem with my setup.
> 
> Could you investigate this, please?

Worked for me but with Zendesk
