### ISSUE TITLE
Use of UIWebView

### ISSUE THREAD

**Issue by shtayner** [usabilla/usabilla-u4a-ios-swift-sdk#205]
We received apple warning to not to use UIWebView anyMore. 
 **_" ITMS-90809: Deprecated API Usage - App updates that use UIWebView will no longer be accepted as of December 2020. Instead, use WKWebView for improved security and reliability._**
Checking with the command line **grep -rnw . -e 'UIWebView'** we found Usabilla using UIWebView  : 
**Binary file ./Pods/Usabilla/Usabilla.framework.dSYM/Contents/Resources/DWARF/Usabilla matches**
Is there a version update coming soon from Usabilla to fix that issue ??
Thanks

**Comment by lennardtastic** [comment]
Hi @shtayner,

Thank you for reaching out.

The Usabilla SDK itself does not use any UIWebViews, we did notice that some of our dependencies we use for testing still use UIWebViews. We'll further investigate this to see if we can take away those dependencies to ensure that the UIWebView won't cause any issues in the future.

Best Regards,
Lennard

**Comment by lennardtastic** [comment]
Hi @shtayner 

I have an update on this, we find the existence of `uiwebview` in `dsym` files and
`.dSYM` files don't contain any functional code it contains debugging metadata.

The reason why you found this mention of `UIWebView` in Usabilla's dSYM is because we link to `UIKit` and the version of iOS that may include `UIWebViews`.

`UIWebViews` don't exist in our actual framework though, which can be confirmed by running the following command:

`nm Usabilla.framework/Usabilla | grep -i UIWebView`

This will return no result. Also see https://github.com/mapbox/ios-sdk-examples/issues/373

If you're using any other third-party frameworks within there app, you may have to confirm using `nm` that there are no other instances of `UIWebView` in your project.

Best regards,
Lennard
