### ISSUE TITLE
iOS privacy disclosure for the Usabillla SDK

### ISSUE THREAD

**Issue by bryce-larson** [usabilla/usabilla-u4a-ios-swift-sdk#214]
As per Apple's new policy:
https://developer.apple.com/news/?id=vlj9jty9
> On each app’s product page, users can learn about some of the data types the app may collect, and whether that data is linked to them or used to track them. You can now enter your app’s privacy information in App Store Connect. This information will be required to submit new apps and app updates to the App Store starting December 8, 2020.

Given the following guidelines:
https://developer.apple.com/app-store/app-privacy-details/

Can you please provide us the privacy details of what / if any data that is being collected by Usabilla so we can disclose on our iOS App Store page.

Branch.io has done a pretty good job as an example:
https://help.branch.io/developers-hub/docs/answer-the-app-store-connect-privacy-questions

Maybe this could be standardised in `ios-privacy.md` file.

**Comment by eduakaszas** [comment]
Hi @bryce-larson , 

Thank you for your message. 

Usabilla for Apps does not have to be disclosed as per the [Apple's privacy guide](https://developer.apple.com/app-store/app-privacy-details/#optional-disclosure). 

If you'd like to disclose it, then we recommend reaching out to your Customer Success Manager to help you define it correctly, since it's connected to the type of data that you're attaching to your feedback items. 

I hope this helps but let me know if you have any questions. 

Kind regards, 
Édua

**Comment by bryce-larson** [comment]
Thank you for getting back to us.
