### ISSUE TITLE
Carthage behavior seems wrong

### ISSUE THREAD

**Issue by cikpis** [usabilla/usabilla-u4a-ios-swift-sdk#26]
Hi guys again :)

After the framework is fetched from carthage, seems that is not moved to ```Carthage/Build/iOS``` but it stay in ```Carthage/Checkouts/usabilla-u4a-ios-swift-sdk```.

Could you check this as well?

**Comment by grimabe** [comment]
Hi @cikpis 

Which version of Carthage are you using (`$ carthage version`) ?
I created a new folder with the following Cartfile inside

```
github "usabilla/usabilla-u4a-ios-swift-sdk" "v3.2.1"

```

And I ran the following command : 

```bash
$ carthage update --platform iOS --verbose
```

got the following output

`*** Downloading usabilla-u4a-ios-swift-sdk.framework binary at "v3.2.1"`

and the framework is inside `Carthage/Build/iOS/`

So it is working for me.

You can eventually try to clean Carthage cache :

```bash
 $ rm -rf ~/Library/Caches/org.carthage.CarthageKit/dependencies/usabilla-u4a-ios-swift-sdk/
 $ rm -rf ~/Library/Caches/org.carthage.CarthageKit/binaries/usabilla-u4a-ios-swift-sdk/
```

**Comment by cikpis** [comment]
Hi @grimabe, 

I'm using ```0.18.1``` but I'm using ```carthage update --platform ios --no-use-binaries``` due to other dependencies.

Can you try to run that?

**Comment by grimabe** [comment]
Now I understand your issue,

`--no-use-binaries` is pretty explicit indeed.

As soon we are publishing the Dynamic framework and not the source code the Carthage build command should be used **without** the `--no-use-binaries` option.

If you absolutely want to use this option because of other repositories then you have **two** options :

* use the path `$(SRCROOT)/Carthage/Checkouts/usabilla-u4a-ios-swift-sdk/UsabillaFeedbackForm.framework` inside the input files of the Carthage build phase of your project
* don't use Carthage and integrate the framework manually if you are not using CocoaPod neither.

**Comment by cikpis** [comment]
Indeed I'm already doing the first option you listed. 

Keep me updated when it will be done on your end. 

Cheers!

**Comment by grimabe** [comment]
@cikpis what do you mean by "done on your end" ?

We are now supporting Carthage through pre-built binary and it is working as expected.

The first solution is the only one to make it working with Carthage if you want to use **--no-use-binaries** option.

**Comment by cikpis** [comment]
I misunderstood you message. I thought you were saying that you'll published the source code as well. Nevermind then.
