### ISSUE TITLE
App store button text not truncated

### ISSUE THREAD

**Issue by MelleI** [usabilla/usabilla-u4a-ios-swift-sdk#45]
We have setup the App Store button with a long text:

'Help ons en laat je beoordeling ook achter in de App store!'

It will be displayed in the app as:

<img width="487" alt="app_store_button" src="https://cloud.githubusercontent.com/assets/19833059/25891444/5d17dac6-3571-11e7-87f6-a2c92884589a.png">

Can you make sure the text is wrapped over multiple line in the button? Is it also possible add some extra options to style the button a bit more? Like a background color.

**Comment by gPinato** [comment]
The multiline text will be corrected immediately and will be available in the next release (a few days from today).

As far as customising the bottom goes, for not it's only possible to set text color, size and font.
I will forward your request to the product team and they will see what we can do.

**Comment by Goseong** [comment]
Hi Melle, 

Thank you for your inquiry.

Regarding the above implementation, we do recommend changing it. Using a large sentence as a link to redirect to the App store does not seem appealing.

In the example above we advise to use the form control called 'Paragraph' on the End page to display the text 'Help ons en laat je beoordeling ook achter in de App store!' And adjust the App store redirect itself into for example: 'Naar de App store.'

Either way, we will create a fix in our upcoming release so that the app store redirect link gets truncated when it does not fit the screen. 
We will be sure to inform you when a new release is available.

**Comment by grimabe** [comment]
HI @MelleI 

In the latest release, we limited the control to only one line and to fit within the screen. It means that the text will be truncated if you provide too many characters.

I know that it does not conform entirely to your request but to respect Apple guidelines we do not want to have a multiple lines button.

Please refer to @Goseong suggested solution above to improve your implementation.

Thanks

**Comment by MelleI** [comment]
Hi @grimabe,

Thanks for the answers and the support. We will fix it with a shorter button text.
