### ISSUE TITLE
Feedback not queued on service unavailable

### ISSUE THREAD

**Issue by quinnthomson** [usabilla/usabilla-u4a-ios-swift-sdk#55]
Feedback is not queued when its submitted and service is unavailable. So feedback caching doesn't work when the device is online, but cannot reach the Usabilla server. The feedback is stored properly when the phone is offline, but not when service is unavailable. 

To recreate:
1. make sure the feedback form is preloaded
2. turn on the network link conditioner to 100% loss
3. fill out and submit feedback
4. see successful submission message
5. turn off network link conditioner so that feedback should succeed
6. feedback is never actually submitted to the Usabilla server

I would expect the feedback to be stored until a successful submission. Am I missing something?

**Comment by grimabe** [comment]
Hi @quinnthomson,

The scenario you are describing seems correct.
Could you please provide us with the following information where the issue is happening: 

- Usabilla SDK version 
- iOS version
- Device model
- Physical device or simulator or both

Thank you

**Comment by quinnthomson** [comment]
Usabilla SDK version 3.6
Confirmed in:
iOS 9.3.5 on physical device iphone 6+
iOS 10.3.2 on physical device iphone 6
iOS 11beta3 on physical device ipad air

Let me know if there's anything else that I can try. 😄

**Comment by gPinato** [comment]
Hi @quinnthomson ,
sorry for the delayed reply.

It seems to be working as intended on our side, tho your case is quite particular.

The SDK listens to the connectivity status to decide whether to send the feedback item or not. The network link conditioner makes all packets fail, but the SDK is still technically connected. This is increasing the time it takes the SDK to respond, because it is waiting for the request to timeout.

This is also making it so that, after restoring the NLC to WIFI, the SDK does not retry immediately because it sees no changes in the connectivity status.

The SDK will try to send the old feedback item if you:
• Send another feedback item
• Close and reopen the hosting app

In the last case, you have to make sure that `UsabillaFeedbackForm.load()` is called. This method will check for unsubmitted feedback items and will send them.
It would be best to call it in the AppDelegate or similar, to make sure it gets called when you app starts up.

Let me know if this fixes the issue.

We will look into improving the connectivity manager and reducing the request timeout time.

**Comment by quinnthomson** [comment]
Hi @gPinato,

I can confirm that feedback is sent once `UsabillaFeedbackForm.load()` is called again. Thanks for helping us out with that!
