### ISSUE TITLE
Unable to Use Swift Usabilla Framework in Objective-C project

### ISSUE THREAD

**Issue by hackiftekhar** [usabilla/usabilla-u4a-ios-swift-sdk#60]
Hello Usabilla,
 
  Thanks for making an awesome product. But I'm having some issues with Usabilla Framework in an Objective-C project. I've installed Usabilla Swift framework in my Objective-C project using CocoaPods. I created my bridging header files correctly. and imported AppName-Swift-h file of Usabilla framework like this

#import <UsabillaFeedbackForm/UsabillaFeedbackForm-Swift.h>

![screen shot 2017-09-07 at 8 05 02 pm](https://user-images.githubusercontent.com/3831495/30204581-96deb11c-94a3-11e7-90c7-de746e0f391e.png)

But the problem with framework is that the UsabillaFeedbackForm-Swift.h file doesn't contain autogenerated class declaration of UsabillaFeedbackForm.swift.

![screen shot 2017-09-07 at 8 05 30 pm](https://user-images.githubusercontent.com/3831495/30204583-96e3fce4-94a3-11e7-99b8-d8701611b119.png)

So my project is unable to recognize UsabillaFeedbackForm class.

![screen shot 2017-09-07 at 8 06 07 pm](https://user-images.githubusercontent.com/3831495/30204580-96db644e-94a3-11e7-8784-e180ef09d2dd.png)
![screen shot 2017-09-07 at 8 06 28 pm](https://user-images.githubusercontent.com/3831495/30204582-96e2ba00-94a3-11e7-90a8-f276f5f43d01.png)

If I try to import like this in my AppName-Swift.h header file
#import <UsabillaFeedbackForm/UsabillaFeedbackForm.Swift>

then it still doesn't work.

Can you please guide me what might be the problem? Can you please provide me any simple demo of Objective-C project?

**Comment by gPinato** [comment]
HI @hackiftekhar ,

I see your problem. Unfortunately, our compatiblity with Obj-C is not the best, but it can work.
Using the framework's method directly from Obj-C currently has some issues.

As suggested in our [small readme guide](https://github.com/usabilla/usabilla-u4a-ios-swift-sdk#integration-with-obj-c-applications), the best way to approach this problem is to use the Usabilla framework is a Swift class, and bridge that class to the rest of your project.

You can extend obj-c classes in swift files to be able to use the framework everywhere in your application.

To do this, there are a few steps:
• Create a bridging header, and import there the Obj-c classes you want to extend / see in swift
• In those Obj-c classes, import `#import "ProductModuleName-Swift.h"` to see the swift files.

At this point, you can create or extend classes in Swift and use the SDK from there.

I have attached a small working project that you can look at to see a very basic implementation.
[Obj-C Test.zip](https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/files/1292130/Obj-C.Test.zip)

Let me know if you have any more issues.

**Comment by hackiftekhar** [comment]
Thanks @gPinato, it works. Thanks for taking a look and preparing the demo for me and other iOS devs to help on this.

**Comment by gPinato** [comment]
No problem.
