### ISSUE TITLE
Question about migrating to Usabilla 4.x

### ISSUE THREAD

**Issue by packatino** [usabilla/usabilla-u4a-ios-swift-sdk#74]
Hi,
I have updated Usabilla to version 4.0.1 in order to being able to build it with Xcode 9.1.
I have read in the change log that I have to initialize Usabilla with an app ID now:

- Renamed `load()` method to `initialize(appID: String?)`. Calling this method is now mandatory to start the SDK.

But I cannot find my app ID anywhere on the Usabilla website when I'm logged in. Could you please give me a hint where I can find that app ID so I can use the SDK again?

I also don't find a way for configuring things like textColor, accentColor and errorColor anymore. Is that not possible anymore?

Best regards
Robert

**Comment by grimabe** [comment]
Hi @packatino 

I will reuse part of my answer from this issue: https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/issues/73#issuecomment-341395523

**If you are using the Campaign feature** you have to provide the **appID** to enable active targeting. This **appID** is an Id that identifies your app in our system and can be created and configured in the [Usabilla Web App](https://app.usabilla.com/member/#/apps/campaigns/overview) .

**If you do not use the campaign feature** you can just use nil as **appID**. The passive feedback will still work.

About the colors, we indeed rethought our public API for the theme and the colors are not customizable anymore from the SDK(except for one of them) this is due to the fact that you can configure the colors within our dashboard in the **Advanced panel** section. So you can change them on the fly without having to update your code.

Hope it answers your questions.

Benjamin

**Comment by packatino** [comment]
Thanks a lot for your quick answer! Since I don't use campaigns I tried it out by passing nil for the app ID and it's working :)
Changing the design on the website makes also sense to me :)
Now I'm happy, thank you very much!

**Comment by grimabe** [comment]
Great to hear! I am closing the issue then.
