### ISSUE TITLE
Custom Parameters

### ISSUE THREAD

**Issue by mariohahn** [usabilla/usabilla-u4a-ios-swift-sdk#82]
Is it possible to set Custom Variables for a Single Form? 

I only found the globales value.

**Comment by gPinato** [comment]
Yes, the custom variables are set globally and are share between all feedback forms, either passive or active.

**Comment by mariohahn** [comment]
Feeldbadman :D 

Are there any plans to add this Feature?

**Comment by gPinato** [comment]
I can forward your request to our product team.
Right now we do not support it because it would be confusing having a global custom variables for the active feedback while having specific ones for passive.

In the meantime, you can still modify the object at runtime and the SDK will pick up all the changes and use the status at the instant the form is displayed.

**Comment by Goseong** [comment]
Hi @mariohahn, can you let me know if this request is still relevant to your app development? What is the use case you are trying to accomplish?

**Comment by mariohahn** [comment]
In our case we would like to know if the user has some streaming Issues. To know the correct channel we need to know the Channel name in the report. So we know which channel has some issues. Furthermore we would like to remove the stars but I don't think that thats possible.

**Comment by Rifinio** [comment]
Hello @mariohahn, 
Since the Custom Variables are global and shared between all the forms, you can still send the Channel name or id by setting the Custom variables just before loading the form!
```swift
Usabilla.customVariables["channel-name"] = "channel name"
Usabilla.customVariables["channel-id"] = "channel-id"
Usabilla.loadFeedbackForm("YOUR_FORM_ID_HERE")
```
Let me know if this answers your question about the Custom Variables.
As for removing the stars, it's currently not possible!

**Comment by mariohahn** [comment]
Yeah i know that, we do that at the moment, but I have to reset the custom Variable after the user submits it.

If there would be custom variables for a form sheet it would be much better

**Comment by Goseong** [comment]
Hi @mariohahn, thank you for your confirmation. We will take this feedback into account.
