### ISSUE TITLE
Localization doesn't cover all possible interface texts

### ISSUE THREAD

**Issue by mohammedDehairy** [usabilla/usabilla-u4a-ios-swift-sdk#86]
so the localization strings keys doesn't cover all interface texts, and its crucial for non-english implementations, like the required fields warningand  texts "Please check the fields marked with *", the title of the form is saying "Feedback" in English and couldn't find any where how to localize it.

and the on the dashboard, specifically for the second form page, the custom text for "Cancel"/"submit" buttons are ignored!.

**Comment by Goseong** [comment]
Hi Mohammed,

Thanks for reaching out. Just to be sure that I understand your situation. You are trying to load a feedback form and having some trouble with its localization is that correct? Or are you working on the campaign (survey) functionality? Let me know so that we can point you in the right direction.

Regards,

Tjerk

**Comment by Goseong** [comment]
Hi @mohammedDehairy,

I can see your problem was resolved through our support desk.

Thanks for reaching out.
