### ISSUE TITLE
Too many symbol files

### ISSUE THREAD

**Issue by Gerrel** [usabilla/usabilla-u4a-ios-swift-sdk#87]
Version 4.0.1 is ok. But since version 4.0.2 I get a error from itunes connect with too many symbol files.

**Comment by Gerrel** [comment]
<img width="661" alt="screen shot 2018-02-08 at 13 17 13" src="https://user-images.githubusercontent.com/391656/35972509-6e182716-0cd2-11e8-8390-aa26d2f983cc.png">

**Comment by gPinato** [comment]
Thank you for the heads up. 
We will look into it. 

Are you sure this is caused by our library and not by any other changes you might have introduced?

**Comment by Gerrel** [comment]
Yes I'm positive. Uploading IPA with version 4.0.1 of UsabillaSDK does not give a error.

**Comment by Goseong** [comment]
Hi @Gerrel, we have reproduced the problem and indeed see that the dSYM files increased significantly on the last release. We will be sure to resolve the problem as part of our next release.

**Comment by gPinato** [comment]
Hello @Gerrel,

Your issue is caused by the fact that the dSYM file provided by us contains the symbols for all architectures ( i386, x86_64, armv7, armv7s and arm64) while your app probably supports only 2 of them (most likely  armv7 and  armv64). 

So iTunes is complaining that the dSYM file contains a bunch of useless files, rightly so.

The problem is that I think we should be shipping those files with our framework to cover all of our clients, and they should be stripped out of the final version of your app when you're archiving it.

I've found a couple of issues reported on both [Cocoapods](https://github.com/CocoaPods/CocoaPods/issues/7111) and [Carthage](https://github.com/Carthage/Carthage/pull/1023) and your same issue has been reported to other framework makers.

Which tool are you using to integrate our SDK into your application? If it's cocoapods, could you make sure you're using the latest version (1.4.0) and that it is correctly configured to strip out unnecessary dsym files?

**Comment by Gerrel** [comment]
I have cocoa pods 1.3.1 at the moment.
I'm currently working on a new release so will check it next week.

**Comment by Gerrel** [comment]
@gPinato 
Confirmed: With Cocoapods 1.4.0 the issue is resolved.
